import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Pretendard 폰트를 위한 Inter 폰트 사용 (한국어 지원)
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-pretendard",
  display: "swap",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={inter.variable}>
      <body className="flex flex-col min-h-screen font-Pretendard bg-gradient-to-br from-blue-50 to-indigo-100">
        {children}
      </body>
    </html>
  );
}
