version: '3.8'

services:
  # TCS Mock Service - 경찰청 TCS API 시뮬레이션
  tcs-mock-service:
    build:
      context: ./backend/tcs-mock-service
      dockerfile: Dockerfile
    container_name: ddp-tcs-mock
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ddp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/api/tcs/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ddp-network:
    driver: bridge