server:
  port: 8085

spring:
  application:
    name: tcs-mock-service
  
  # H2 데이터베이스 설정 (개발용)
  datasource:
    url: jdbc:h2:mem:tcsdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2 콘솔 활성화 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console

# Eureka 클라이언트 설정
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# 로깅 설정
logging:
  level:
    com.ddp.tcs: DEBUG
    org.springframework.web: DEBUG