# API Gateway 설정 (포트폴리오용)
# 마이크로서비스 라우팅 및 CORS 설정

server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        # Auth Service 사용자 라우팅
        - id: auth-service-users
          uri: lb://auth-service
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /users/$\{segment}
        
        # Auth Service JWT 라우팅  
        - id: auth-service-jwt
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /auth/$\{segment}
      
      # 개발 친화적 CORS 설정
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:3000" # Next.js 프론트엔드
              - "http://localhost:8080" # API Gateway
              - "*" # 개발용으로 모든 오리진 허용
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

# API Gateway 로깅 설정 (개발용)
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
    org.springframework.web: DEBUG

# 액추에이터 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway