# API Gateway 설정 (포트폴리오용)
# 마이크로서비스 라우팅 및 CORS 설정

server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        # Auth Service 사용자 라우팅
        - id: auth-service-users
          uri: lb://auth-service
          predicates:aa
            - Path=/api/users/**

        # Auth Service JWT 라우팅  
        - id: auth-service-jwt
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        # TCS Mock Service 라우팅
        - id: tcs-mock-service
          uri: lb://tcs-mock-service
          predicates:
            - Path=/api/tcs/**

# API Gateway 로깅 설정 (개발용)
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){magenta} %clr(%-5level){highlight} %clr(%logger{36}){cyan} - %msg%n"
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
    org.springframework.web: DEBUG

# 액추에이터 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway