# API Gateway 설정 (포트폴리오용)
# 마이크로서비스 라우팅 및 CORS 설정

server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
      # ==================== Device Service (Specific Routes) ====================
      # Device Service 사용자 조치 라우팅 (Auth Service보다 우선순위 높아야 함)
      - id: device-service-user-actions
        uri: lb://device-service
        predicates:
        - Path=/api/v1/users/*/actions

      # ==================== Auth Service ====================
      # Auth Service 사용자 라우팅
      - id: auth-service-users
        uri: lb://auth-service
        predicates:
        - Path=/api/v1/users/**

      # Auth Service JWT 라우팅
      - id: auth-service-jwt
        uri: lb://auth-service
        predicates:
        - Path=/api/v1/auth/**

      # ==================== TCS Mock Service ====================
      # TCS Mock Service 라우팅 (공개 API)
      - id: tcs-mock-service
        uri: lb://tcs-mock-service
        predicates:
        - Path=/api/v1/tcs/**

      # ==================== Company Service ====================
      # Company Service 관리자 API
      - id: company-service-admin
        uri: lb://company-service
        predicates:
        - Path=/api/v1/admin/companies/**

      # Company Service 업체 포털 API
      - id: company-service-portal
        uri: lb://company-service
        predicates:
        - Path=/api/v1/company/portal/**

      # Company Service 서비스 기록 API
      - id: company-service-records
        uri: lb://company-service
        predicates:
        - Path=/api/v1/company/service-records/**

      # Company Service 내부 API
      - id: company-service-internal
        uri: lb://company-service
        predicates:
        - Path=/api/v1/companies/**

      # Company Service 공개 API
      - id: company-service-public
        uri: lb://company-service
        predicates:
        - Path=/api/v1/public/operators/**

      # ==================== Reservation Service ====================
      # Reservation Service 관리자 API
      - id: reservation-service-admin
        uri: lb://reservation-service
        predicates:
        - Path=/api/v1/admin/reservations/**

      # Reservation Service 사용자 API
      - id: reservation-service-user
        uri: lb://reservation-service
        predicates:
        - Path=/api/v1/reservations/**

      # Reservation Service 업체 API
      - id: reservation-service-company
        uri: lb://reservation-service
        predicates:
        - Path=/api/v1/reservations/company/**

      # ==================== Device Service ====================
      # Device Service API (장치 관리)
      - id: device-service
        uri: lb://device-service
        predicates:
        - Path=/api/v1/devices/**

      # Device Service API (로그 관리)
      - id: device-service-logs
        uri: lb://device-service
        predicates:
        - Path=/api/v1/logs/**

      # Device Service API (관리자 조치)
      - id: device-service-admin-actions
        uri: lb://device-service
        predicates:
        - Path=/api/v1/admin/actions/**, /api/v1/admin/*/actions, /api/v1/admin/logs/*/actions

      # Device Service API (조치 확인)
      - id: device-service-actions-read
        uri: lb://device-service
        predicates:
        - Path=/api/v1/actions/**

# JWT 설정 (auth-service와 동일한 시크릿 사용)
jwt:
  secret: ${JWT_SECRET:myDevelopmentSecretKeyForDDPProject32Chars}
  issuer: ddp-gateway

# API Gateway 로깅 설정 (개발용)
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){magenta} %clr(%-5level){highlight} %clr(%logger{36}){cyan} - %msg%n"
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
    org.springframework.web: DEBUG

# 액추에이터 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
