# Auth Service 설정 (포트폴리오용)
# 사용자 관리 및 JWT 인증 서비스

server:
  port: 8082

spring:
  application:
    name: auth-service
  
  # H2 인메모리 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # H2 콘솔 설정
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  
  # Redis 설정 (로컬)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

# JWT 설정
jwt:
  secret: myDevelopmentSecretKeyForDDPProject32Chars
  access-token-expiration: 3600 # 1시간
  refresh-token-expiration: 604800 # 7일

# Auth Service 로깅 설정
logging:
  level:
    com.ddp.auth: DEBUG
    org.springframework.security: INFO
    org.springframework.data.redis: INFO
    org.hibernate.SQL: DEBUG